server:
  port: 9000

kafka.topic: topic_leo_test

spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      properties:
        schema:
          registry:
            url: http://localhost:8081